apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fruit-canary-v1
  labels:
    app: fruit-canary
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: fruit-canary
    spec:
      containers:
      - name: fruit-canary
        image: hashicorp/http-echo
        args:
          - "-text=apple"
        ports:
        - containerPort: 5678

---

kind: Service
apiVersion: v1
metadata:
  name: fruit-service-canary
spec:
  type: LoadBalancer
  selector:
    app: fruit-canary
  ports:
    - port: 5678 # Default port for image