apiVersion: v1
kind: Service 
metadata:
  name: kafka-connect-fluentd-service
  namespace: observability
spec:
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    app: kafka-connect-fluentd
  type: LoadBalancer
