apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-fluentd-service
  namespace: observability
spec:
  type: LoadBalancer
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: kafka-connect-fluentd
