apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager-api-david
  namespace: platform
  labels:
    app: user-manager-api-david
spec:
  replicas: 5
  selector:
    matchLabels:
      app: user-manager-api-david
  template:
    metadata:
      labels:
        app: user-manager-api-david
    spec:
      containers:
      - name: user-manager-api
        image: acrsatrack.azurecr.io/user-manager-api:1.14.11
        imagePullPolicy: Always
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 600m
            memory: 600Mi
      imagePullSecrets:
      - name: registrosatrack
---
apiVersion: v1
kind: Service
metadata:
  name: user-manager-api-david
  namespace: platform
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: user-manager-api-david
