apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager-api-alex
  namespace: platform
  labels:
    app: user-manager-api-alex
spec:
  replicas: 5
  selector:
    matchLabels:
      app: user-manager-api-alex
  template:
    metadata:
      labels:
        app: user-manager-api-alex
    spec:
      containers:
      - name: user-manager-api
        image: acrsatrack.azurecr.io/user-manager-api:1.14.13
        imagePullPolicy: Always
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
      imagePullSecrets:
      - name: registrosatrack
---
apiVersion: v1
kind: Service
metadata:
  name: user-manager-api-alex
  namespace: platform
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: user-manager-api-alex
