apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fruit-bg-v1
  labels:
    app: fruit-bg
    version: v1.0.0
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: fruit-bg
        version: v1.0.0
    spec:
      containers:
      - name: fruit-bg
        image: hashicorp/http-echo
        args:
          - "-text=apple"
        ports:
        - containerPort: 5678

---

kind: Service
apiVersion: v1
metadata:
  name: fruit-service-bg
spec:
  type: LoadBalancer
  selector:
    app: fruit-bg
    version: v1.0.0
  ports:
    - port: 5678 # Default port for image
  