apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit-bg-v2
  labels:
    app: fruit-bg
spec:
  replicas: 3
  
  selector:
    matchLabels:
      app: fruit-bg
      version: v2.0.0
  
  template:
    metadata:
      labels:
        app: fruit-bg
        version: v2.0.0
    spec:
      containers:
      - name: fruit-bg
        image: hashicorp/http-echo
        args:
          - "-text=banana"
        ports:
        - containerPort: 5678